### ISSUE TITLE
Advise to allow wss://ws.gleap.io in content-security-policy with version 12

### ISSUE THREAD

**Issue by abenhamdine** [GleapSDK/JavaScript-SDK#29]
Starting from v12, Gleap use websockets.
I think the changelog should mention as a breaking change that wss://ws.gleap.io should be now allowed in content-security-policy, otherwise (like in our app), the sdk will break.

**Comment by boehlerlukas** [comment]
Hey @abenhamdine,

Thanks a lot for the input and sorry for the inconvenience. Will add it to the release notes right now. It's also available here:
https://docs.gleap.io/javascript/content-security-policy

Best,
Lukas
