### ISSUE TITLE
Filtering network logs issue

### ISSUE THREAD

**Issue by AlisaStefan** [GleapSDK/JavaScript-SDK#41]
Hello,

I need to filter from the network logs some nested keys, and reading the [documentation](https://docs.gleap.io/javascript/network-logs#set-filter-with-code) it looks like I can do that by using` Gleap.setNetworkLogPropsToIgnore(["api-key", "user.password", "..."])`. 

The actual behaviour is that the nested keys are not removed. It seems like only top level keys are filtered.

We are using Graphql and our requests payload are in a format of 
```
"variables": {  "input": {
"key1": "value"  ,
"key2": "value"
}}
```
Trying to filter only `key2` won't work.

**Comment by boehlerlukas** [comment]
Hey @AlisaStefan thanks for opening this issue. We will happily look into it and get back to you as soon as possible.

One thing to try in the meantime would be to add `variables.input.key2`.

Best,
Lukas

**Comment by AlisaStefan** [comment]
@boehlerlukas I already tried that and the key is not removed
