### ISSUE TITLE
`Gleap.updateContact()` types don't allow `null` to remove data

### ISSUE THREAD

**Issue by gustavopch** [GleapSDK/JavaScript-SDK#47]
This should be possible:

> ## Removing data
> Update are run incrementally. If you want to remove data, you can do so by adding a key value pair with null as value.
> ```ts
> Gleap.updateContact({
>   keyToDelete: null
> });
> ```
> — https://docs.gleap.io/javascript/user-identity#removing-data

But the types don't allow `null`:
https://github.com/GleapSDK/JavaScript-SDK/blob/98804a6988b25323acaea106d70f7c26440ba061/index.d.ts#L120-L131

**Comment by boehlerlukas** [comment]
@gustavopch great catch! This got fixed with v13.7.8.
