### ISSUE TITLE
Missing safe area insets

### ISSUE THREAD

**Issue by gustavopch** [GleapSDK/JavaScript-SDK#48]
<img width="414" alt="image" src="https://github.com/user-attachments/assets/a7cea910-0761-41d5-888d-f9bbe321e559">

It should use something like `padding-bottom: env(safe-area-inset-bottom)`.

**Comment by boehlerlukas** [comment]
@gustavopch could you share on which iOS version this happens? We will happily look into this :)

**Comment by gustavopch** [comment]
@boehlerlukas I was assuming on all iOS versions, but I've tested with an iPhone XR (iOS 17.5.1).
