### ISSUE TITLE
Problem to minify gleap import module

### ISSUE THREAD

**Issue by rafaeldev** [GleapSDK/JavaScript-SDK#50]
I'm using gleap as module for my esbuild asset build and it works well on development env. When run in production it throws this erron on browser:
```gleap-9de9b8833f137bb0008190229964003ecf6f6b06e994a528d3a27b4cb38cc652.js:124 Uncaught SyntaxError: Unexpected identifier 'interactive' (at gleap-9de9b8833f137bb0008190229964003ecf6f6b06e994a528d3a27b4cb38cc652.js:124:340)```

That's fails everytime which try minify gleap file.

A good test is try minify gleap before usage

**Comment by rafaeldev** [comment]
Debugging this problem deeper and that appears to be a problem with esbuild minify engine.

I created a repo and here it works well 
https://github.com/rafaeldev/gleap-minify-test

**Comment by boehlerlukas** [comment]
Hey @rafaeldev 

Thanks a lot for reporting the bug! Were you able to solve it by changing the esbuild engine? We are currently on public holidays - will happily take a look into it on Monday.

**Comment by rafaeldev** [comment]
@boehlerlukas I can't solve this. I'm skipping minify for gleap on my esbuild for my rails application.

My guess is anything about rails build asset ecosystem.
I will try to spend few hours looking that behavior

**Comment by rafaeldev** [comment]
https://gist.github.com/rafaeldev/c31e467503cd773edcd37e6f2b557e1e

I found the point of the problem. I don't know why what code replaces `sourceMappingURL` with a bad formatted code, so resulting in the error.

Line 124 from gist => `(y?"//# sourceMappingURL="+y:"")`

The interesting part is I put `minify` config parameter at esbuild.config to false skipping.

Let me know if it isn't clear

**Comment by rafaeldev** [comment]
Investigating more I found a sprockets lib behavior where it apply replace from "//# sourceMappingURL=" string to literal code [at this line](https://github.com/GleapSDK/JavaScript-SDK/blob/31c1fcab1b48ccf904cbc73e9abf1db5da69da64/src/RRWebRecorder.js#L2086). Definitively isn't gleap problem 👍🏾

**Comment by boehlerlukas** [comment]
@rafaeldev thanks a lot for debugging into it at this depth! Would you suggest we somehow escape this string differently to try if the minifier still creates invalid JS? Do you thing"//# is the problem?
